Shap Hell's Gate: IpAddrPool Class Reference
IpAddrPool Class Reference
#include <ipaddrpool.h>
Public Member Functions
IpAddrPool ()=default
~IpAddrPool ()=default
void pushBack (const IpAddr &addr)
template<typename... Ts>
void emplaceBack (Ts... args)
void sortDescending ()
IpAddrPool filter (const std::initializer_list< uint8_t > &filterValuesList)
IpAddrPool filterAny (uint8_t filterValue)
void print ()
Private Attributes
std::vector< IpAddr > m_data
Detailed Description
Definition at line 17 of file ipaddrpool.h.
Constructor & Destructor Documentation
IpAddrPool()
IpAddrPool::IpAddrPool () default
~IpAddrPool()
IpAddrPool::~IpAddrPool () default
Member Function Documentation
emplaceBack()
template<typename... Ts> void IpAddrPool::emplaceBack (Ts... args) inline
Definition at line 23 of file ipaddrpool.h.
    {
        m_data.emplace_back(args...);
    }
Referenced by Reader::getPool(), and ip_filter_fixture::ip_filter_fixture().
filter()
IpAddrPool IpAddrPool::filter (const std::initializer_list< uint8_t > & filterValuesList)
Definition at line 15 of file ipaddrpool.cpp.
{
    IpAddrPool subPool;
    if(filterValuesList.size() > IpAddr::length)
    {
        throw std::length_error("Initializer list is out of range");
    }
    for(const auto& addrToFilter : m_data)
    {
        uint8_t i = 0;
        bool isPassed = true;
        for(const auto filterValue : filterValuesList)
        {
            if(addrToFilter.data[i] != filterValue)
            {
                isPassed = false;
                break;
            }
            ++i;
        }
        if(isPassed)
        {
            subPool.pushBack(addrToFilter);
        }
    }
    return subPool;
}
Referenced by main(), TEST_F(), and TEST_F().
filterAny()
IpAddrPool IpAddrPool::filterAny (uint8_t filterValue)
Definition at line 43 of file ipaddrpool.cpp.
{
    IpAddrPool subPool;
    for(const auto& addrToFilter : m_data)
    {
        for(int i = 0; i < IpAddr::length; ++i)
        {
            if(addrToFilter.data[i] == filterValue)
            {
                subPool.pushBack(addrToFilter);
                break;
            }
        }
    }
    return subPool;
}
Referenced by main(), and TEST_F().
print()
void IpAddrPool::print ()
Definition at line 60 of file ipaddrpool.cpp.
{
    for(const IpAddr& ipAddr: m_data)
    {
        std::cout << (int)ipAddr.data[0] << "."
                  << (int)ipAddr.data[1] << "."
                  << (int)ipAddr.data[2] << "."
                  << (int)ipAddr.data[3] << std::endl;
    }
}
Referenced by main(), TEST_F(), TEST_F(), and TEST_F().
pushBack()
void IpAddrPool::pushBack (const IpAddr & addr)
Definition at line 3 of file ipaddrpool.cpp.
{
    m_data.push_back(addr);
}
Referenced by filter(), and filterAny().
sortDescending()
void IpAddrPool::sortDescending ()
Definition at line 8 of file ipaddrpool.cpp.
{
    std::sort(m_data.begin(), m_data.end(), [](const IpAddr& lhs, const IpAddr& rhs){
        return lhs.data > rhs.data;
    });
}
Referenced by ip_filter_fixture::ip_filter_fixture(), and main().
Member Data Documentation
m_data
std::vector<IpAddr> IpAddrPool::m_data private
Definition at line 33 of file ipaddrpool.h.
Referenced by emplaceBack(), filter(), filterAny(), print(), pushBack(), and sortDescending().
The documentation for this class was generated from the following files:
hw2-ip-filtering/ipaddrpool.h
hw2-ip-filtering/ipaddrpool.cpp