Shap Hell's Gate: hw1-build-test-deploy/lib.h File Reference
lib.h File Reference
#include <string>
#include "version.h"
Functions
bool isVersionGreater (std::string v1, std::string v2)
Compares two versions represented as strings in format "n1.n2.n3" like (1.12.52).
std::string version ()
Function Documentation
isVersionGreater()
bool isVersionGreater (std::string v1, std::string v2)
Compares two versions represented as strings in format "n1.n2.n3" like (1.12.52).
Parameters
v1 Version (string) to check.
v2 Version (string) to check with.
Returns
true if v1 > v2, false otherwise.
Todo
Error checks for input strings.
Definition at line 3 of file lib.cpp.
{
    /* Stores integer value of each part of version. */
    int vnum1 = 0, vnum2 = 0;
    for(int i = 0, j = 0; (i < v1.length() || j < v2.length());)
    {
        /* Convert one part of version to number. */
        while(i < v1.length() && v1[i] != '.')
        {
            vnum1 = vnum1 * 10 + (v1[i] - '0');
            i++;
        }
        /* Convert other part of version to number. */
        while(j < v2.length() && v2[j] != '.')
        {
            vnum2 = vnum2 * 10 + (v2[j] - '0');
            j++;
        }
        /* Compare part of versions. */
        if(vnum1 > vnum2)
        {
            return true;
        }
        else if(vnum1 < vnum2)
        {
            return false;
        }
        else
        {
            /* Reset number variables and go for next numeric part. */
            vnum1 = vnum2 = 0;
            i++;
            j++;
            continue;
        }
    }
    return false;
}
Referenced by BOOST_AUTO_TEST_CASE(), and main().
version()
std::string version ()
Definition at line 44 of file lib.cpp.
{
    return std::string(PROJECT_VERSION);
}
Referenced by BOOST_AUTO_TEST_CASE(), and main().