name: 'C++ CI'

on:
  push:
    tags:
      - '*'

jobs:
  helloworld:
    name: HelloWorld
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake ./hw1-build-test-deploy -DWITH_BOOST_TEST=ON
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          allowUpdates: true
      - name: Upload Release Asset 1
        id: upload-release-asset-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./helloworld-${{ github.ref_name }}-Linux.deb
          asset_name: helloworld-${{ github.ref_name }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
  ip_filter:
    name: Ip Filter
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libgtest-dev libgmock-dev && sudo apt-get install libtbb-dev
      - run: cmake ./hw2-ip-filtering -DWITH_GTEST=ON
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          allowUpdates: true
      - name: Upload Release Asset 2
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ip_filter-${{ github.ref_name }}-Linux.deb
          asset_name: ip_filter-${{ github.ref_name }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
